/* THIS QUERY CREATES A NEW DATABASE IN THE MYSQL SERVER */
CREATE DATABASE COMPANY;
SHOW DATABASES;
USE COMPANY;

/* THIS QUERY CREATES A NEW TABLE IN THE SPECIFIED DATABASE */
CREATE TABLE employees(emp_id int primary key not null unique,emp_name varchar(20),emp_dept varchar(40),joining_date date,emp_manager_name varchar(30),working_shift varchar(10));

/* THIS QUERY INSERTS DATA INTO A SPECIFIED TABLE */
INSERT INTO employees(emp_id , emp_name , emp_dept , joining_date , emp_manager_name , working_shift) VALUES
(001,'AMAN PANDEY','SOFTWARE DEVELOPMENT','2014-09-10','LOVE BABAR','MORNING'),
(002,'NAMAN PANDEY','DATA SCIENCE AND ANALYTICS','2022-03-23','HARRY','MORNING'),
(003,'SANDEEP SINGH','SOFTWARE DEVELOPMENT','2014-05-11','SHRADHA KHAPRA','EVENING'),
(004,'ANSHUMAAN SINGH','CLOUD INFRASTRUCTURE','2019-01-02','HARRY','NIGHT'),
(005,'ARYAN YADAV','SOFTWARE DEVELOPMENT','2024-06-16','LOVE BABAR','MORNING');

/* THIS QUERY SELECTS ALL THE COLUMNS AND ROWS FROM THE SPECIFIED TABLE */
SELECT * FROM employees;

/* THIS QUERY DROPS (DELETES) THE SPECIFIED TABLE FROM THE DATABASE */ 
DROP TABLE employees;